package org.igt.enums;

/**
 * ENUm to hold Property file keys.
 * Mar 14, 2023
 * @author Mandeep Sheoran
 * @version 1.0
 * @since 1.0
 */
public enum PropertiesType {
	BASEURL,
	SENDRESULTSTOELK,
	DASHBOARDURL,		
	URL,
	PORTALUSERNAME,
	PORTALPASSWORD,
	OVERRIDEREPORTS,
	PASSEDSTEPSSCREENSHOT,
	FAILEDSTEPSSCREENSHOT,
	SKIPPEDSTEPSSCREENSHOT,
	FAILEDRETRYTESTS,
	RUNMODE,
	SELENIUMGRIDURL,
	ELKURL,
	BROWSER,
	LGAUNITYURL,
	NOTIFICATIONURL,
	AIRPORTDASHBOARDURL
}
